src/Entity/Token.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TokenRepository")
 */
class Token
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="tokens", cascade={"persist"})
     */
    private $user_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $value;

    public function __construct(User $user)
    {
        $this->created_at = new \DateTime();
        $this->user = $user;
        $this->value = md5(uniqid());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;
        
        return $this;
    }

    public function getValue(): ?string
    {
        return $this->value;
    }

    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function isValid()
    {
        $interval = new \DateInterval('PT30M');

        return $this->created_at->add($interval) >= new \DateTime();
    }
}

src/Entity/Trick.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TrickRepository")
 * @UniqueEntity("name")
 */
class Trick
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=3, 
     * max=255, 
     * minMessage="Le nom du trick doit contenir au minimun {{ limit }} caractères",
     * maxMessage="Le nom du trick doit contenir moins de {{ limit }} caractères"
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=3,
     * minMessage="La description du trick doit contenir au minimun {{ limit }} caractères"
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $modified_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PictureTrick", mappedBy="relation", cascade={"persist", "remove"})
     */
    private $pictureTricks;


    /**
     * @Assert\Image(
     * mimeTypes= {"image/jpeg", "image/jpg", "image/png"},
     * mimeTypesMessage = "Veuillez selectionner une image en .jpg, .jpeg ou .png",
     * minHeight = 300,
     * minHeightMessage = "La hauteur de l'image est trop petite, minimum 300",
     * minWidth = 300,
     * minWidthMessage = "La largeur de l'image est trop petite, minimum 300",
     * maxSize = "2m",
     * maxSizeMessage = "L'image est trop grosse, kappa!, 2 mo Max !",
     * allowPortrait = false,
     * allowPortraitMessage = "Les images en portrait ne sont pas autorisées",
     * minRatio = 1.5,
     * )
     */
    private $defaultPicture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nameDefaultPicture;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\VideoTrick", mappedBy="relation", cascade={"persist", "remove"})
     */
    private $videoTricks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="trick", cascade={"persist", "remove"})
     */
    private $comments;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->pictureTricks = new ArrayCollection();
        $this->videoTricks = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        $this->id;
        return $this->id;
    }

    public function setId($id): ?int
    {
        $this->id =$id;
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getModifiedAt(): ?\DateTimeInterface
    {
        return $this->modified_at;
    }

    public function setModifiedAt(?\DateTimeInterface $modified_at): self
    {
        $this->modified_at = $modified_at;

        return $this;
    }

    /**
     * @return Collection|PictureTrick[]
     */
    public function getPictureTricks(): Collection
    {
        return $this->pictureTricks;
    }

    public function addPictureTrick(PictureTrick $pictureTrick): self
    {
        if (!$this->pictureTricks->contains($pictureTrick)) {
            $this->pictureTricks[] = $pictureTrick;
            $pictureTrick->setRelation($this);
        }

        return $this;
    }

    public function removePictureTrick(PictureTrick $pictureTrick): self
    {
        if ($this->pictureTricks->contains($pictureTrick)) {
            $this->pictureTricks->removeElement($pictureTrick);
            // set the owning side to null (unless already changed)
            if ($pictureTrick->getRelation() === $this) {
                $pictureTrick->setRelation(null);
            }
        }

        return $this;
    }

    public function getDefaultPicture(): ?UploadedFile
    {
        return $this->defaultPicture;
    }
    public function setDefaultPicture(UploadedFile $defaultPicture): self
    {
        $this->defaultPicture = $defaultPicture;
        return $this;
    }

    public function getNameDefaultPicture(): ?string
    {
        return $this->nameDefaultPicture;
    }

    public function setNameDefaultPicture(string $nameDefaultPicture): self
    {
        $this->nameDefaultPicture = $nameDefaultPicture;

        return $this;
    }

    /**
     * @return Collection|VideoTrick[]
     */
    public function getVideoTricks(): Collection
    {
        return $this->videoTricks;
    }

    public function addVideoTrick(VideoTrick $videoTrick): self
    {
        if (!$this->videoTricks->contains($videoTrick)) {
            $this->videoTricks[] = $videoTrick;
            $videoTrick->setRelation($this);
        }

        return $this;
    }

    public function removeVideoTrick(VideoTrick $videoTrick): self
    {
        if ($this->videoTricks->contains($videoTrick)) {
            $this->videoTricks->removeElement($videoTrick);
            // set the owning side to null (unless already changed)
            if ($videoTrick->getRelation() === $this) {
                $videoTrick->setRelation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setTrick($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getTrick() === $this) {
                $comment->setTrick(null);
            }
        }

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Trick;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label' => "Nom du trick"])
            ->add('description', TextareaType::class, [
                'label' => "Description",
                'attr' => ['rows' => 5]])
            ->add('category', ChoiceType::class, [
                'label' => "Catégorie",
                'choices' => [
                    'Grabs' => "Grabs",
                    'Rotations' => "Rotations",
                    'Flips' => "Flips",
                    'Rotations désaxées' => "Rotations désaxées",
                    'Slides' => "Slides",
                    'Old school' => "Old school",
                ]
            ])
            ->add('defaultPicture', FileType::class, [
                'label' => 'Ajouter une image en avant:',
                'required' => true,
                'multiple' => false,
            ])
            ->add('pictureTricks', CollectionType::class, [
                'entry_type' => TrickPictureType::class,
                'entry_options' => [
                    'label' => false
                ],
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('videoTricks', CollectionType::class, [
                'entry_type' => VideoType::class,
                'entry_options' => [
                    'label' => false
                ],
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

templates/trick/addTrick.html.twig
{% extends 'base.html.twig'  %}

{% block title %}
Ajouter un trick
{% endblock %}

{% block body %}

<div class="container mt-4">
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            <h1 class="h3 mb-3 font-weight-normal">Créer un trick</h1>
        </div>
    </div>
    {{ form_start(form) }}
    <div class="row justify-content-md-center">
        <div class="col-md-8 mt-2">
            {{ form_row(form.name) }}
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-8 mt-2">
            {{ form_row(form.defaultPicture) }}
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {{ form_row(form.description) }}
        </div>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {{ form_row(form.category) }}
        </div>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <hr>
        </div>
    </div>

    <div class="row justify-content-md-center">
        <ul class="pictureTricks col-md-8"
            data-prototype="{{ form_widget(form.pictureTricks.vars.prototype)|e('html_attr') }}">
            {% for pictureTrick in form.pictureTricks %}
            <li class="list-unstyled">{{ form_row(pictureTrick.file) }}</li>

            
            {% endfor %}
        </ul>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-md-5">
            <hr>
        </div>
    </div>

    <div class="row justify-content-md-center">
        <ul class="videoTricks col-md-8"
            data-prototype="{{ form_widget(form.videoTricks.vars.prototype)|e('html_attr') }}">
            {% for videoTricks in form.videoTricks %}
            <li class="list-unstyled">{{ form_row(videoTricks.url) }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="row justify-content-md-center">
        <div class="col-md-8 mt-2 mb-5">
            <button class="btn btn-success mb-2">Créer le trick</button>
        </div>
    </div>
    {{ form_end(form) }}
</div>

{% endblock %}

templates/trick/editTrick.html.twig
{% extends 'base.html.twig'  %}

{% block title %}
{{trick.name}}
{% endblock %}

{% block body %}

{% for message in app.flashes('success')%}
<div class="row justify-content-md-center mt-4">
    <div class="col-md-4">
        <div class="alert alert-success">
            {{ message }}
        </div>
    </div>
</div>
{% endfor %}

<div class="border container mt-5">
    <div class="row">
        <div id="header_trick" class="col">
            {% if trick.nameDefaultPicture == 'NULL' %}
            <header class="masthead card-img-top"
                style=" background-image: url({{ asset('images/NoImageFound.png') }});">
                {% else %}
                <header class="masthead card-img-top"
                    style=" background-image: url({{ asset('uploads/'~ trick.nameDefaultPicture) }});">
                    {% endif %}

                    <form method="POST" action="{{ path('trick_delete_default_picture', {id: trick.id}) }}"
                        onsubmit="return confirm('Etes-vous sûr de vouloir supprimer ma photo à la une ?')"
                        style="z-index: 1;">
                        <input type="hidden" name="_method" value="POST">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trick.id )}}">
                        <button class="btn btn-danger float-right m-2">
                            <img src="{{ asset('images/trash-alt-solid.svg') }}" height="16px">
                        </button>
                    </form>

                    <a href="{{path('trick_add_picture', {id: trick.id}) }}">
                        <button class="btn btn-warning float-right m-2 ">
                            <img src="{{ asset('images/pencil-alt-solid.svg') }}" height="16px">
                        </button>
                    </a>

                    <div class="intro-text">
                        <div class="intro-lead-in">
                            <h1>{{ trick.name }}</h1>
                        </div>
                    </div>
                </header>
        </div>
    </div>

    <div class="d-flex justify-content-center" onclick="myFunction()">
        <button id="show_media" class="btn btn-info mt-3 see_media">Voir les médias</button>
    </div>
    <div class="see_media" id="see_media">
        <div class="d-flex align-content-start flex-wrap mt-3">
            {% for picture in pictures %}
            <div class="col-md-3 col-sm-6 mt-2">
                <div class="card card-home m-1">
                    <img class="card-img-top" src="{{ asset('uploads/'~ picture.name) }}" alt="" width="416px"
                        height="200px">
                    <div class="card-body d-flex justify-content-end">
                        <form method="POST" action="{{ path('trick_delete_picture', {id: picture.id}) }}"
                            onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cette photo ?')">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ picture.id )}}">
                            <button class="btn btn-danger mr-3">
                                <img src="{{ asset('images/trash-alt-solid.svg') }}" height="16px">
                            </button>
                        </form>
                        <a class="btn btn-warning" href="{{path('trick_edit_picture', {id: picture.id}) }}">
                            <img src="{{ asset('images/pencil-alt-solid.svg') }}" height="16px">
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}


            {% for video in videos %}
            <div class="col-md-3 col-sm-6 mt-2">
                <div class="card card-home m-1">
                    <div class="embed-responsive" style="height:200px; width:237px;">
                        {{ video.url|raw }}
                    </div>
                    <div class="card-body d-flex justify-content-end">
                        <form method="POST" action="{{ path('trick_delete_video', {id: video.id}) }}"
                            onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cette vidéo ?')">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ video.id )}}">
                            <button class="btn btn-danger mr-3">
                                <img src="{{ asset('images/trash-alt-solid.svg') }}" height="16px">
                            </button>
                        </form>
                        <a class="btn btn-warning" href="{{path('trick_edit_video', {id: video.id}) }}">
                            <img src="{{ asset('images/pencil-alt-solid.svg') }}" height="16px">
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="container mt-4">
        {{ form_start(form) }}
        <div class="row justify-content-md-center">
            <div class="col-md-8 mt-2">
                {{ form_row(form.name) }}
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {{ form_row(form.description) }}
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                {{ form_row(form.category) }}
            </div>
        </div>
        <div class="row justify-content-md-center mb-5">
            <div class="col-md-8 mt-2">
                <button class="btn btn-primary">Modifier le trick</button>
            </div>
        </div>
        {{ form_end(form) }}
    </div>


</div>

{% endblock %}

templates/trick/loadMoreComments.html.twig
{% for comment in comments %}
<li class="media mb-3">
    {% if comment.userId.pictureUser.name is not defined %}
    <img class="mt-3 mr-2 rounded-circle" src="/images/default_picture.jpeg" height="100px" width="100px">
    {% else %}
    <img class="mt-3 mr-2 rounded-circle" src="{{ asset('uploads/'~ comment.userId.pictureUser.name) }}" height="100px"
        width="100px">
    {% endif %}
    <div class="media-body ">
        <div class="card">
            <div class="card-body">
                <h5 class="mt-0 mb-1 card-title">{{ comment.userId.username | upper }}</h5>

                <p class="card-text">{{ comment.content | nl2br }}</p>

                <span class="badge badge-primary float-right">le
                    {{ comment.createdAt | date('d-m-Y à H:i') }}</span>
            </div>
        </div>
    </div>
</li>
{% endfor %}

templates/trick/showTrick.html.twig
{% extends 'base.html.twig'  %}

{% block title %}
{{trick.name}}
{% endblock %}

{% block body %}

{% for message in app.flashes('success')%}
<div class="row justify-content-md-center mt-4">
    <div class="col-md-4">
        <div class="alert alert-success">
            {{ message }}
        </div>
    </div>
</div>
{% endfor %}

<div class="border container mt-5">

    <div class="row">
        <div id="header_trick" class="col">
            {% if trick.nameDefaultPicture == 'NULL' %}
            <header class="masthead card-img-top" style=" background-image: url({{ asset('images/NoImageFound.png') }});">
            {% else %}
            <header class="masthead card-img-top" style=" background-image: url({{ asset('uploads/'~ trick.nameDefaultPicture) }});">
            {% endif %}
                <div class="intro-text">
                    <div class="intro-lead-in">
                        <h1>{{ trick.name }}</h1>
                    </div>
                </div>
            </header>
        </div>
    </div>

    <div class="d-flex justify-content-center" onclick="myFunction()">
        <button id="show_media" class="btn btn-info mt-3 see_media">Voir les médias</button>
    </div>
    <div class="see_media" id="see_media">
        <div id="media" class="d-flex align-content-start flex-wrap mt-3">
            {% for picture in pictures %}
            <div class="p-2">
                <img src="{{ asset('uploads/'~ picture.name) }}" height="150px" width="200px">
            </div>
            {% endfor %}


            {% for video in videos %}
            <div class="p-2 mt-2 ml-2 mr-2 embed-responsive embed-responsive-16by9" style="width:200px; height:150px">
                {{ video.url|raw }}
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="row ml-4 mt-4">
        <p class="mb-3 font-weight-normal">{{trick.description | nl2br}}</p>
    </div>

    <div class="d-flex justify-content-center">
        <div class="p-2">
            <span class="list-group-item list-group-item-primary">Catégorie: {{trick.category}}</span>
        </div>
        <div class="p-2">
            <span class="list-group-item list-group-item-secondary">Ajouté le:
                {{trick.createdAt | date('d-m-Y')}}</span>
        </div>
        {% if not trick.modifiedAt == null %}
        <div class="p-2">
            <span class="list-group-item list-group-item-dark">Modifié le:
                {{trick.modifiedAt | date('d-m-Y')}}</span>
        </div>
        {% endif %}
    </div>

    {% if is_granted('ROLE_USER') %}
    <hr>

    {{form_start(form)}}

    <div class="row justify-content-md-center">
        <div class="col-md-6">
            {{ form_row(form.content) }}
            {{ form_row(form.submit) }}
        </div>
    </div>

    {{form_end(form)}}
    {% endif %}

    {% if not app.user %}
    <hr>
    <div class="row mb-2">
        <div class="col-md-8 ml-auto mr-auto mb-2">
            <p class="text-center">Vous pouvez commenter ce trick en vous <a class="btn btn-outline-info"
                    href="{{ path('app_login') }}">connectant</a> ou en <a class="btn btn-outline-info"
                    href="{{path('inscription')}}">enregistrant</a></p>
        </div>
    </div>
    {% endif %}

    <hr>
    {% if comments is empty %}
    <div class="row mb-2">
        <div class="col-md-8 ml-auto mr-auto mb-2">
            <h4 class="text-center mb-4">Il n'y a pas de commentaire pour le moment</h4>
        </div>
    </div>
    {% else %}
    <div class="row mb-2">
        <div class="col-md-8 ml-auto mr-auto mb-2">
            <h4 class="text-center mb-4">Commentaires</h4>
            <ul class="list-unstyled" id="commentList">
                {% for comment in comments %}
                <li class="media mb-3">
                    {% if comment.userId.pictureUser.name is not defined %}
                    <img class="mt-3 mr-2 rounded-circle" src="/images/default_picture.jpeg" height="100px"
                        width="100px">
                    {% else %}
                    <img class="mt-3 mr-2 rounded-circle" src="{{ asset('uploads/'~ comment.userId.pictureUser.name) }}"
                        height="100px" width="100px">
                    {% endif %}
                    <div class="media-body ">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="mt-0 mb-1 card-title">{{ comment.userId.username | upper }}</h5>

                                <p class="card-text">{{ comment.content | nl2br }}</p>

                                <span class="badge badge-primary float-right">le
                                    {{ comment.createdAt | date('d-m-Y à H:i') }}</span>
                            </div>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <div class="row mt-3 mb-3">
                <a class="m-auto" id="loadMoreCommentBTN">
                    <button class="btn btn-primary ">Voir plus</button>
                </a>
            </div>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}
{% block javascripts %}

<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    click = 0;
    $("#btn-up").hide();

    function loadMoreComment(event) {
        event.preventDefault();
        click++;
        let comment = 5 * click;
        const url = "{{ path('load_more_comment' , {category: trick.category, id: trick.id}) }}" + '/' + comment;
        axios.get(url).then(function (response) {
            $("#commentList").append(response.data);
            if (comment === 5) {
                $("#btn-up").show();
            }
        }).catch(function (error) {
            if (error.response.status === 404) {
                window.alert("Erreur ! la page demander n'existe pas.");
            } else {
                window.alert("Alert une erreure c'est produite veuillez contacter le support !");
            }
        });
    }

    document.getElementById('loadMoreCommentBTN').addEventListener('click', loadMoreComment);
</script>
{% endblock %}